"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const express_validator_1 = require("express-validator");
const appointments_controller_1 = require("../controllers/appointments.controller");
const appointment_validator_1 = require("../validators/appointment.validator");
const router = (0, express_1.Router)();
router.get('/', appointments_controller_1.getAppointments);
router.get('/:id', appointments_controller_1.getAppointment);
router.post('/', appointment_validator_1.validateAppointment, appointments_controller_1.createAppointment);
router.put('/:id', appointment_validator_1.validateAppointment, appointments_controller_1.updateAppointment);
router.delete('/:id', appointments_controller_1.deleteAppointment);
router.patch('/:id/status', (0, express_validator_1.body)('status').isIn(['pendiente', 'confirmada', 'cancelada']), appointments_controller_1.updateStatus);
exports.default = router;
